In [10]:
%config IPCompleter.greedy = True
#   Above is for the IntelliSense module to work.
import tensorflow as tf
#   To prevent a total meltdown of my GPU, restrictions needed to be made.
rtx2080 = tf.config.experimental.list_physical_devices('GPU')
for num in rtx2080:
    tf.config.experimental.set_memory_growth(num, True)
print('Go ahead')

Go ahead


In [11]:
import numpy as np
import tensorflow as tensorflow
from d2l import tensorflow as d2l

true_w = tf.constant([2,-3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)


As we can see, in this book - we'll be doing the same damn thing just as the earlier one, 
except that we shall call the higher council magic of KERAS, the TensorFlow High-Level API for DL/ML.

In [12]:
def load_array(data_arrays, batch_size, is_train = True):
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[-0.25415364,  0.452938  ],
        [ 0.9286384 , -1.7490934 ],
        [ 0.6678283 , -0.22204627],
        [-0.7659453 ,  0.15152474],
        [-0.06647165,  1.5990258 ],
        [-0.15157346,  0.2951088 ],
        [ 0.7398171 , -2.759268  ],
        [-0.15879342,  0.26650652],
        [ 1.453479  ,  0.5748983 ],
        [ 0.05668436,  0.20966102]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 2.14065  ],
        [11.99943  ],
        [ 6.284743 ],
        [ 2.15122  ],
        [-1.3549905],
        [ 2.8910851],
        [15.061181 ],
        [ 2.9596896],
        [ 5.1659794],
        [ 3.6098025]], dtype=float32)>)

In [13]:
#   Now the high council magic shit:
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

loss = tf.keras.losses.MeanSquaredError()

trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True),y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f"epoch {epoch + 1}, loss {1:f}")

AttributeError: 'Sequential' object has no attribute 'trainable_varibles'

In [ ]:
w = net.get_weights()[0]
print(f"Error in estimating w:", true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print(f"Error in estimating b:", true_b - b)