In [2]:
%config IPCompleter.greedy = True
#   Above is for the IntelliSense module to work.
import tensorflow as tf
gpus = len(tf.config.experimental.list_physical_devices('GPU'))
print(f"So you've got {gpus} soul(s) in your hands, eh?\nWell, goodluck and Godspeed.")

#   To prevent a total meltdown of my GPU, restrictions needed to be made.
rtx2080 = tf.config.experimental.list_physical_devices('GPU')
for num in rtx2080:
    tf.config.experimental.set_memory_growth(num, True)

So you've got 1 soul(s) in your hands, eh?
Well, goodluck and Godspeed.


**Creating a sample tensor**

In [3]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [4]:
a = x.shape
b = tf.size(x)
print(a,b)
#   Note that the damn thing is kinda the same, just different ways of seeing it - I guess.

(12,) tf.Tensor(12, shape=(), dtype=int32)


In [5]:
X = tf.reshape(x, (3,4)); print('This is X', X)

#   Now we reshape the thing so that it becomes a 3x4 matrix - still a tensor(-ish, with one two dimension so technically it is.)
#   Good thing about ML and tensors are that they are quite smart, watch this shit.
J = tf.reshape(x, (-1,4)); print('And this is J', J)

#   Where the -1 states that "Do it yourself, blockheaded bitch."

This is X tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
And this is J tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)


In [6]:
#   In a real use case however, we wanna populate these tensors with useful datas,
#   either zeroes or ones, or even random distributions.
#   For zeros:
zeroes = tf.zeros((2,3,4))
#   My guesss is that create a Tensor with (2) dimensions, with each dimension of (3) by (4)
#   I don't know, I'm new to this.
#   For ones:
ones = tf.ones((2,3,4))
zeroes, ones

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=float32)>)

In [7]:
#   As stated before, we wanted a data in there, so for this purposes - lets do a Normal (Gaussian) Distribution random function:
tf.random.normal(shape=[2, 3, 4])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-2.0948133 , -0.1436514 ,  0.659115  ,  1.3215209 ],
        [-0.7327848 , -1.4577098 ,  0.03880419, -1.0673419 ],
        [-0.28489622,  0.62033564,  0.685288  ,  0.45897585]],

       [[ 1.1391335 ,  0.3063209 ,  0.7682058 , -1.6338375 ],
        [-0.59788406, -0.24085988, -0.64743227, -2.0702207 ],
        [ 0.6423083 ,  0.5162608 ,  0.04243708, -1.1106051 ]]],
      dtype=float32)>

In [8]:
#   Now lets do some Operations, note that due to the nature of this - all of the operators are now performing
#   As an ELEMENTWISE operations. ก็คือ "ทำแม่งทั้งก้อน" -SY (2021).
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x, y, x+y, x-y, x*y, x/y, x**y, tf.exp(x)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 4., 8.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 2., 2., 2.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=
 array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
       dtype=float32)>)

In [9]:
#   Remember that "np.append" bullshit, now he has grown into 'concatenate'-tion:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3,4))
Y = tf.constant([[2.0,1,4,3], [1,2,3,4], [4,3,2,1]], dtype=tf.float32)
#   What is intriguing is that the first tensor element of a constant tensor, must be 
#   a goddamn float, else the damn thing just collapses.
#   Ok I know now, this is due to the fact that the X tensor is a float type, and if 
#   we don't specify the Y tensor as a float, it would kill itself.
tf.concat([X,Y], axis = 0), tf.concat([X,Y], axis = 1)

(<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 8), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]], dtype=float32)>)

In [10]:
#   This can also be operated through boolean
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [11]:
#   And to 'shrink' it all into 1x1:
tf.reduce_sum(X)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

## Automatic Differentiation
Suppose we want to find a derivative of:
y = 2x^T x; where dy/dx  
*which in our world is: y = 2x^2*

In [14]:
x = tf.range(4, dtype = tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [17]:
#   Before we go any further, we have to now ACTUALLY store it. Wow.
x = tf.Variable(x)
#   Then we can calculate:
with tf.GradientTape() as t:
    y = 2*tf.tensordot(x, x, axes=1)

#   Which we can now find the gradient of the scalars output
x_grad = t.gradient(y,x)
y, x_grad

(<tf.Tensor: shape=(), dtype=float32, numpy=28.0>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.,  4.,  8., 12.], dtype=float32)>)

In [18]:
#   Now we should get [0 4 8 12]; which means that at x = 0, it is 0 and so on.
#   Hence, intuitively - we can say that the derivative of this function is 4x.
#   Lets proove that its true.
x_grad == 4 * x

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [19]:
#   This can also be done in a way such as:
#   y = x^2 = x * x
with tf.GradientTape() as t:
    y = x * x
t.gradient(y,x)
#   Which is, you guessed it - 2x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 2., 4., 6.], dtype=float32)>